Models/ErrorViewModel.cs
namespace ExerciceFakeDb.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/Monkey.cs
using System.ComponentModel;

namespace ExerciceFakeDb.Models
{
    public class Monkey
    {
        public int Id {     get; set; }

        [DisplayName("Prénom")]
        public string Name { get; set; }
        public Monkey() { }
        public Monkey(string name) : this()
        {
            Name = name;
        }

    }
}

Models/MonkeyGenerator.cs
using ExerciceFakeDb.Data;

namespace ExerciceFakeDb.Models
{
    public class MonkeyGenerator
    {
        public FakeDb FakeDb { get; set; }
        public List<string> MonkeyName { get; set; }

        public Random rnd { get; set; } = new Random();
        public MonkeyGenerator()
        {
            MonkeyName = new List<string>()
            {
                "Stuart",
                "Fitzgerald",
                "Bonsai",
                "Hariette",
                "Peanut",
                "Sawa",
                "Rafiki",
                "Thunderstomp",
                "Po",
                "Chen",
                "Pickles",
                "Jean",
                "Maurice",
                "Julian",
                "Fred",
                "Albert",
                "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
                "Bonk",
                "Bingus",
                "Bongus",
                "Daenerys de typhon de la Maison Targaryen, première du nom, Reine de Meereen, Reine des Andals, de Rhoynar et des Premiers Hommes, Suzeraine des Sept Couronnes et Protectrice du Royaume, Khaleesi de la Grande Mer Herbeuse, Mère des Dragons, L'Imbrûlée"
            };
        }



        public string GenerateName()
        {
            return MonkeyName[rnd.Next(0, MonkeyName.Count)];
        }
    }
}

Controllers/HomeController.cs
using ExerciceFakeDb.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace ExerciceFakeDb.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {

            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/MonkeyController.cs
using ExerciceFakeDb.Data;
using ExerciceFakeDb.Models;
using ExerciceFakeDb.Repositories;
using Microsoft.AspNetCore.Mvc;

namespace ExerciceFakeDb.Controllers
{
    public class MonkeyController : Controller
    {


        public MonkeyRepository Repository { get; set; }



        public MonkeyGenerator Generator { get; set; }

        public MonkeyController(IRepository<Monkey> repository, MonkeyGenerator generator)
        {

            Repository = (MonkeyRepository?)repository;
            Generator = generator;
        }
        public IActionResult Index()
        {
           

            return View(Repository.GetAll());
        }

        public string Add()
        {
            return "Pas encore implémenté";
        }

        public IActionResult Details(int id)
        {
            Monkey monkey = Repository.GetById(id);
            return View(monkey);
        }

        public IActionResult GenerateRandom()
        {
            Repository.Create(new Monkey()
            {
                Name = Generator.GenerateName(),
            });

            
            return RedirectToAction(nameof(Index));
        }

        public IActionResult Delete(int id)
        {
            Repository.Delete(id);
            return RedirectToAction(nameof(Index));

        }
    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Monkey/Details.cshtml
@model Monkey
@{
}
<div class="card" style="width: 18rem;">
@*     <img src="..." class="card-img-top" alt="..."> *@
    <div class="card-body">
        <h5 class="card-title">@Model.Name</h5>
        <p class="card-text">Un petit singe très sympathique.</p>
        <a href="#" class="btn btn-primary">Donne une cacahuète au singe</a>

    </div>
</div>

Views/Monkey/Index.cshtml
@model List<Monkey>
@{
}

<table class="table">
    <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">@Html.DisplayNameForInnerType((Monkey m) => m.Name)</th>
            <th scope="col"></th>
        </tr>
    </thead>
    <tbody>
        @{
            foreach (var monkey in Model)
            {
                <tr>
                    <th scope="row">@monkey.Id</th>
                    <td>@monkey.Name</td>
                    <td><a class="btn btn-danger" asp-action="Delete" asp-route-id="@monkey.Id">X</a></td>
                </tr>
            }
        }
    </tbody>
</table>
<a class="btn btn-primary" asp-action="GenerateRandom">Ajouter un singe aléatoire</a>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ExerciceFakeDb</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ExerciceFakeDb.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ExerciceFakeDb</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle text-dark" href="#" data-bs-toggle="dropdown" aria-expanded="false">Singes</a>
                            <ul class="dropdown-menu">
                                <li><a class="dropdown-item text-dark" asp-controller="Monkey" asp-action="Index">Mes singes</a></li>
                                <li><a class="dropdown-item text-dark" asp-controller="Monkey" asp-action="Add">Ajouter un singe</a></li>
                                <li><a class="dropdown-item text-dark" asp-controller="Monkey" asp-action="GenerateRandom">Génére un singe</a></li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - ExerciceFakeDb - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>